sudo: required
cache:
  - apt: true
  - pip: true

services:
  - docker

language: generic

matrix:
  include:
  - name: "bionic melodic"
    dist: bionic

install:
  - sudo docker build -t aisaac:rostest .

script:
  - sudo docker run -it --rm --name aisaac_test aisaac:rostest
