language: generic

services:
  - docker

matrix:
  include:
  - name: "bionic melodic"

before_install:
  - docker build -t aisaac:rostest .

script:
  - docker run -it --rm --name aisaac_test aisaac:rostest
