sudo: required

services:
  - docker

language: generic

matrix:
  include:
  - name: "bionic melodic"
    dist: bionic

before_install:
  - sudo docker pull osrf/ros:melodic-desktop-full || true

install:
  - sudo docker build -t aisaac:rostest .

script:
  - sudo docker run -it --rm --name aisaac_test aisaac:rostest

 cache:
    directories:
     - /var/lib/docker
