sudo: required

services:
  - docker

language: generic

matrix:
  include:
  - name: "bionic melodic"
    dist: bionic

# before_install:
#   # Load cached docker images
#   - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  # - sudo docker pull osrf/ros:melodic-desktop-full
  - sudo docker build -t aisaac:rostest .

script:
  - sudo docker run -it --rm --name aisaac_test aisaac:rostest

# before_cache:
#   - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | grep 'melodic' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

# cache:
#   directories:
#     - $HOME/docker
